service: gikou
provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"
  timeout: 300

functions:
  gikou:
    handler: build/index.default
    events:
      - http:
         method: get
         path: gikou
         cors: true
    memorySize: 1536
